### ISSUE TITLE
Game Model

### ISSUE THREAD

**Issue by Oneman2feet** [octref/MesmerGL#2]
Port over game model code to CUGL, making changes to its organization to provide a clean interface for the controller to work with.

Need to provide (in rough order of priority):
 - modular class design
 - a clean representation of game state in object-oriented fashion
 - efficient methods for slice rotation
 - a way to construct a board state given a representation of a "level"
 - a way to determine if mesmer can travel from one grid position to another, and the path if so

**Comment by qqsantaclaus** [comment]
Check "models" branch for impl.
I ignore shelf for now and will add it in if we decide to have it.
Need more testing, but code works fine with my small tests.
